### PR TITLE
Dev divradix2

### PR DESCRIPTION
**Pull request by bitpasta**
Added radix-2 divider which is supposed to be smaller than the existing radix-4 divider.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Thanks :D

**Comment by Dolu1990** [comment]
I did some tests, it seems it is all good with behaviour and performance, also, this pr divider is smaller than the legacy one (configured with radix2), but when the area parameter is cleared, the area and fmax reaaaaaly take a big hit.

```
rv32i_d1_l1_rfa_rsrc -> (no divider)
Artix 7 -> 90 Mhz 1151 LUT 952 FF 
Artix 7 -> 189 Mhz 1249 LUT 952 FF 
rv32i_d1_l1_rfa_rsrc_d2Area -> (This PR divider with area set)
Artix 7 -> 90 Mhz 1374 LUT 1058 FF    (divRadix4 reworked to support radix 2 is around 1400 LUT)
Artix 7 -> 203 Mhz 1482 LUT 1058 FF 
rv32i_d1_l1_rfa_rsrc_d2 -> (This PR divider with area cleared)
Artix 7 -> 71 Mhz 1747 LUT 1092 FF 
Artix 7 -> 94 Mhz 1882 LUT 1094 FF 
rv32i_d1_l1_rfa_rsrc_d4Area -> (DivRadix4)
Artix 7 -> 90 Mhz 1576 LUT 1123 FF 
Artix 7 -> 197 Mhz 1699 LUT 1123 FF 
```

I generated those using the vexiiriscv.scratchpad.IntegrationSynthBench
It need a vivado environnement variable : 
ex on my setup : 
export VIVADO_ARTIX_7_BIN="/media/data2/tools/xilinx/Vivado/2023.1/bin"

Note if you used it, rv32i_d1_l1_rfa_rsrc_d2 will not use this pr divider, but the legacy one. (unlike in the number above)

**Comment by bitpasta** [comment]
Cool, thanks for the evaluation! :D
You mean the `lowArea` config flag?
Having `lowArea = false` was kind of an experiment to be slightly faster in some cases (skipping zeros). Might be really not worth it.

**Comment by Dolu1990** [comment]
> lowArea = false

yes right.
I guess that fine, for the lowArea = false, the parameter generator will use the reworked DivRadix4.

Thanks ^^

**Pull request merged**
